Added the Login/Register components folder and drivers
FrancoA56/FinalProjectClient pull request #2
Opened 2023-09-26 20:15 UTC by Corto07

Login and register components created

2023-09-26 20:30 UTC, zTom1909 approved these changes
## Quick note
There's a spelling error in the registerComponent (Sign instead of Sing)

2023-09-26 20:33 UTC, FrancoA56 approved these changes

2023-09-26 20:33 UTC, zTom1909 requested changes
## Change request
You also seem to forgot the import of LoginComponents at your login view!

2023-09-26 20:35 UTC, FrancoA56 requested changes
Chance the branch Main to dev

2023-09-27 11:33 UTC, nahuelnob approved these changes

2023-09-27 14:30 UTC, Jimemateo approved these changes

2023-09-27 16:14 UTC, FrancoA56 approved these changes

2023-09-27 19:54 UTC, zTom1909 approved these changes

2023-09-27 23:56 UTC, merged